//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveTWpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>NGasAug21</string>
  <string>CopperJul21</string>
  <string>AUDCAD</string>
  <string>AUDNZD</string>
  <string>AUDUSD</string>
  <string>CADJPY</string>
  <string>EURCHF</string>
  <string>EURJPY</string>
  <string>EURUSD</string>
  <string>NZDUSD</string>
  <string>USDCAD</string>
  <string>USDCHF</string>
  <string>USDJPY</string>
  <string>Ger30</string>
  <string>Usa500</string>
  <string>UsaInd</string>
  <string>UsaTec</string>
  <string>GOLD</string>
  <string>SILVER</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Symbols {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Symbols"]));
            }
        }
    }
}
